import {IPerformance} from "@/app/types";

const Performances: IPerformance[] = [
	{
		id: 1,
		performer: "Mimi Fatale",
		artist: "Blanche",
		song: "City Lights",
		country: "Belgique",
		year: 2017,
		flag_url: "flags/belgique.png",
		small_drag_urls: ["performers/mimi-sm.png"],
		full_drag_urls: ["performers/mimi.png"],
	},
	{
		id: 2,
		performer: "Kitty Catcher",
		artist: "France Gall",
		song: "Poupée de cire",
		country: "Luxembourg",
		year: 1965,
		flag_url: "flags/luxembourg.png",
		small_drag_urls: ["performers/kitty-sm.png"],
		full_drag_urls: ["performers/kitty.png"],
	},
	{
		id: 3,
		performer: "Coco Nutz",
		artist: "Hera Björk",
		song: "Je ne sais quoi",
		country: "Islande",
		year: 2010,
		flag_url: "flags/islande.png",
		small_drag_urls: ["performers/coco-sm.png"],
		full_drag_urls: ["performers/coco.png"],
	},
	{
		id: 4,
		performer: "Lady Monrose",
		artist: "DQ",
		song: "Drama Queen",
		country: "Danemark",
		year: 2007,
		flag_url: "flags/danemark.png",
		small_drag_urls: ["performers/ladymonrose-sm.png"],
		full_drag_urls: ["performers/ladymonrose.png"],
	},
	{
		id: 5,
		performer: "Ella & Coco",
		artist: "Verka Serduchka",
		song: "Dancing Lasha Tumbai",
		country: "Ukraine",
		year: 2007,
		flag_url: "flags/ukraine.png",
		small_drag_urls: ["performers/ella-sm.png", "performers/coco-sm.png"],
		full_drag_urls: ["performers/ella.png", "performers/coco.png"],
	},
	{
		id: 6,
		performer: "Mimi Fatale",
		artist: "Elena Tsagrinou",
		song: "El Diablo",
		country: "Chypre",
		year: 2021,
		flag_url: "flags/chypre.png",
		small_drag_urls: ["performers/mimi-sm.png"],
		full_drag_urls: ["performers/mimi.png"],
	},
	{
		id: 7,
		performer: "Kitty Catcher",
		artist: "Laureen",
		song: "Tattoo",
		country: "Suède",
		year: 2023,
		flag_url: "flags/suede.png",
		small_drag_urls: ["performers/kitty-sm.png"],
		full_drag_urls: ["performers/kitty.png"],
	},
	{
		id: 8,
		performer: "Ella Vale",
		artist: "Céline Dion",
		song: "Ne partez pas sans moi",
		country: "Suisse",
		year: 1988,
		flag_url: "flags/suisse.png",
		small_drag_urls: ["performers/ella-sm.png"],
		full_drag_urls: ["performers/ella.png"],
	},
	{
		id: 9,
		performer: "Lady Monrose",
		artist: "La Zarra",
		song: "Évidemment",
		country: "France",
		year: 2023,
		flag_url: "flags/france.png",
		small_drag_urls: ["performers/ladymonrose-sm.png"],
		full_drag_urls: ["performers/ladymonrose.png"],
	},
	{
		id: 10,
		performer: "Kelly D",
		artist: "Conchita Wurst",
		song: "Rise Like a Phoenix",
		country: "Autriche",
		year: 2014,
		flag_url: "flags/autriche.png",
		small_drag_urls: ["performers/kelly-sm.png"],
		full_drag_urls: ["performers/kelly.png"],
	},
];
export default Performances;
